<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // Oli & Pelumas
            [
                'category_id' => 1,
                'supplier_id' => 3,
                'code' => 'OLI001',
                'name' => 'Oli Mesin Yamalube 10W-40 0.8L',
                'description' => 'Oli mesin motor matic premium',
                'type' => 'sparepart',
                'buy_price' => 45000,
                'sell_price' => 55000,
                'stock' => 50,
                'min_stock' => 10,
                'unit' => 'botol',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 1,
                'supplier_id' => 3,
                'code' => 'OLI002',
                'name' => 'Oli Mesin MPX2 Honda 0.8L',
                'description' => 'Oli mesin Honda untuk motor bebek dan sport',
                'type' => 'sparepart',
                'buy_price' => 40000,
                'sell_price' => 50000,
                'stock' => 45,
                'min_stock' => 10,
                'unit' => 'botol',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Sparepart Mesin
            [
                'category_id' => 2,
                'supplier_id' => 1,
                'code' => 'MSN001',
                'name' => 'Busi NGK Iridium',
                'description' => 'Busi iridium performa tinggi',
                'type' => 'sparepart',
                'buy_price' => 75000,
                'sell_price' => 95000,
                'stock' => 30,
                'min_stock' => 5,
                'unit' => 'pcs',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 2,
                'supplier_id' => 1,
                'code' => 'MSN002',
                'name' => 'Piston Kit Honda Beat',
                'description' => 'Piston kit original Honda Beat',
                'type' => 'sparepart',
                'buy_price' => 180000,
                'sell_price' => 220000,
                'stock' => 8,
                'min_stock' => 3,
                'unit' => 'set',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Kelistrikan
            [
                'category_id' => 3,
                'supplier_id' => 2,
                'code' => 'ELK001',
                'name' => 'Aki Yuasa GTZ5S 12V 5Ah',
                'description' => 'Aki motor maintenance free',
                'type' => 'sparepart',
                'buy_price' => 200000,
                'sell_price' => 250000,
                'stock' => 15,
                'min_stock' => 5,
                'unit' => 'pcs',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 3,
                'supplier_id' => 2,
                'code' => 'ELK002',
                'name' => 'Lampu LED H6 Philips',
                'description' => 'Lampu LED depan motor',
                'type' => 'sparepart',
                'buy_price' => 85000,
                'sell_price' => 110000,
                'stock' => 20,
                'min_stock' => 5,
                'unit' => 'pcs',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Ban
            [
                'category_id' => 5,
                'supplier_id' => 2,
                'code' => 'BAN001',
                'name' => 'Ban IRC 90/90-14 Tubeless',
                'description' => 'Ban motor matic tubeless',
                'type' => 'sparepart',
                'buy_price' => 165000,
                'sell_price' => 200000,
                'stock' => 12,
                'min_stock' => 4,
                'unit' => 'pcs',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Rem
            [
                'category_id' => 6,
                'supplier_id' => 1,
                'code' => 'REM001',
                'name' => 'Kampas Rem Depan Vario',
                'description' => 'Kampas rem depan original Honda Vario',
                'type' => 'sparepart',
                'buy_price' => 35000,
                'sell_price' => 45000,
                'stock' => 25,
                'min_stock' => 5,
                'unit' => 'set',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Filter
            [
                'category_id' => 7,
                'supplier_id' => 1,
                'code' => 'FLT001',
                'name' => 'Filter Udara Honda Beat',
                'description' => 'Filter udara original Honda Beat',
                'type' => 'sparepart',
                'buy_price' => 25000,
                'sell_price' => 35000,
                'stock' => 4,
                'min_stock' => 5,
                'unit' => 'pcs',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Jasa Service
            [
                'category_id' => 8,
                'supplier_id' => null,
                'code' => 'JSA001',
                'name' => 'Jasa Service Ringan',
                'description' => 'Ganti oli, cek kelistrikan, cek rem',
                'type' => 'jasa',
                'buy_price' => 0,
                'sell_price' => 35000,
                'stock' => 0,
                'min_stock' => 0,
                'unit' => 'service',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 8,
                'supplier_id' => null,
                'code' => 'JSA002',
                'name' => 'Jasa Service Besar',
                'description' => 'Overhaul mesin, bongkar CVT, tune up',
                'type' => 'jasa',
                'buy_price' => 0,
                'sell_price' => 150000,
                'stock' => 0,
                'min_stock' => 0,
                'unit' => 'service',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 8,
                'supplier_id' => null,
                'code' => 'JSA003',
                'name' => 'Jasa Ganti Ban',
                'description' => 'Jasa pemasangan ban baru',
                'type' => 'jasa',
                'buy_price' => 0,
                'sell_price' => 15000,
                'stock' => 0,
                'min_stock' => 0,
                'unit' => 'service',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('fm_products')->insertBatch($data);
    }
}
